name = "better-sweet-drinks-feedback"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGINS = "https://bettersweetdrinks.com,https://www.bettersweetdrinks.com"

[[d1_databases]]
binding = "DB"
database_name = "better-sweet-drinks-feedback"
database_id = "090b76b6-5457-4e8f-8b5e-787919d56aa0"
